insert into authors (first_name, last_name) values ('Willabella', 'McGinly');
insert into authors (first_name, last_name) values ('Margarete', 'Haycox');
insert into authors (first_name, last_name) values ('Whitney', 'Portriss');
insert into authors (first_name, last_name) values ('Lem', 'Hayen');
insert into authors (first_name, last_name) values ('Car', 'Fritzer');
insert into authors (first_name, last_name) values ('Lise', 'Kiss');
insert into authors (first_name, last_name) values ('Hillary', 'Basezzi');
insert into authors (first_name, last_name) values ('Skye', 'Redbourn');
insert into authors (first_name, last_name) values ('Danit', 'Olivelli');
insert into authors (first_name, last_name) values ('Kitty', 'Dormer');
insert into authors (first_name, last_name) values ('Ardith', 'Assinder');
insert into authors (first_name, last_name) values ('Urson', 'Matessian');
insert into authors (first_name, last_name) values ('Alva', 'Dewes');
insert into authors (first_name, last_name) values ('Anny', 'Phlippsen');
insert into authors (first_name, last_name) values ('Virgie', 'Rubinsohn');
insert into authors (first_name, last_name) values ('Alfred', 'Melsom');
insert into authors (first_name, last_name) values ('Fara', 'Gillingwater');
insert into authors (first_name, last_name) values ('Judd', 'Allison');
insert into authors (first_name, last_name) values ('Rania', 'Senter');
insert into authors (first_name, last_name) values ('Loutitia', 'Alstead');
insert into authors (first_name, last_name) values ('Neville', 'Berresford');
insert into authors (first_name, last_name) values ('Sherie', 'Mahoney');
insert into authors (first_name, last_name) values ('Sheilah', 'Tomik');
insert into authors (first_name, last_name) values ('Vidovic', 'Cattle');
insert into authors (first_name, last_name) values ('Madlin', 'Stoffer');
insert into authors (first_name, last_name) values ('Olivia', 'Ramshay');
insert into authors (first_name, last_name) values ('Udall', 'Dormer');
insert into authors (first_name, last_name) values ('Etta', 'Stockford');
insert into authors (first_name, last_name) values ('Joel', 'Lampens');
insert into authors (first_name, last_name) values ('Alikee', 'Bickley');
insert into books (author_id, title, price_old, price) values (11, 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author_id, title, price_old, price) values (8, 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (author_id, title, price_old, price) values (9, 'extend strategic e-services', '$272.00', '$151.04');
insert into books (author_id, title, price_old, price) values (7, 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (author_id, title, price_old, price) values (12, 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author_id, title, price_old, price) values (15, 'architect vertical ROI', '$282.54', '$102.61');
insert into books (author_id, title, price_old, price) values (7, 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author_id, title, price_old, price) values (1, 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author_id, title, price_old, price) values (9, 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author_id, title, price_old, price) values (3, 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author_id, title, price_old, price) values (4, 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (author_id, title, price_old, price) values (12, 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author_id, title, price_old, price) values (5, 'scale integrated architectures', '$257.66', '$32.97');
insert into books (author_id, title, price_old, price) values (14, 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (author_id, title, price_old, price) values (15, 'strategize B2B channels', '$232.27', '$44.83');
insert into books (author_id, title, price_old, price) values (16, 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author_id, title, price_old, price) values (17, 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author_id, title, price_old, price) values (14, 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author_id, title, price_old, price) values (9, 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author_id, title, price_old, price) values (10, 'target innovative paradigms', '$298.94', '$130.01');
insert into books (author_id, title, price_old, price) values (21, 'generate open-source e-business', '$276.57', '$113.25');
insert into books (author_id, title, price_old, price) values (2, 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author_id, title, price_old, price) values (10, 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author_id, title, price_old, price) values (4, 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author_id, title, price_old, price) values (2, 'facilitate efficient eyeballs', '$232.30', '$131.48');