package com.github.flotskiy.FlotskiyBookShopApp.model.entity.author;

import com.github.flotskiy.FlotskiyBookShopApp.model.entity.book.BookEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.Set;

@Entity
@Table(name = "author")
@ApiModel(description = "data model of author entity")
public class AuthorEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "this id generated by db", position = 1)
    private int id;

    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty(value = "author's photo in accordance with the prescribed format", position = 2)
    private String photo;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty(value = "mnemonic author's ID displayed as a link to his page", position = 3)
    private String slug;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty(
            value = "author's first and last (if applicable) names", example = "First_name Last_name", position = 4)
    private String name;

    @Column(columnDefinition = "TEXT")
    @ApiModelProperty(value = "info about author", position = 5)
    private String description;

    @ManyToMany(mappedBy="authorEntities")
    private Set<BookEntity> books;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<BookEntity> getBooks() {
        return books;
    }

    public void setBooks(Set<BookEntity> books) {
        this.books = books;
    }
}
